export const consonants = [
  { char: "ㄱ", romaji: "g/k", sound: "g", group: "basic-consonants" },
  { char: "ㄴ", romaji: "n", sound: "n", group: "basic-consonants" },
  { char: "ㄷ", romaji: "d/t", sound: "d", group: "basic-consonants" },
  { char: "ㄹ", romaji: "r/l", sound: "r", group: "basic-consonants" },
  { char: "ㅁ", romaji: "m", sound: "m", group: "basic-consonants" },
  { char: "ㅂ", romaji: "b/p", sound: "b", group: "basic-consonants" },
  { char: "ㅅ", romaji: "s", sound: "s", group: "basic-consonants" },
  { char: "ㅇ", romaji: "ng/silent", sound: "ng", group: "basic-consonants" },
  { char: "ㅈ", romaji: "j", sound: "j", group: "basic-consonants" },
  { char: "ㅊ", romaji: "ch", sound: "ch", group: "aspirated-consonants" },
  { char: "ㅋ", romaji: "k", sound: "k", group: "aspirated-consonants" },
  { char: "ㅌ", romaji: "t", sound: "t", group: "aspirated-consonants" },
  { char: "ㅍ", romaji: "p", sound: "p", group: "aspirated-consonants" },
  { char: "ㅎ", romaji: "h", sound: "h", group: "aspirated-consonants" },
  { char: "ㄲ", romaji: "kk", sound: "kk", group: "tense-consonants" },
  { char: "ㄸ", romaji: "tt", sound: "tt", group: "tense-consonants" },
  { char: "ㅃ", romaji: "pp", sound: "pp", group: "tense-consonants" },
  { char: "ㅆ", romaji: "ss", sound: "ss", group: "tense-consonants" },
  { char: "ㅉ", romaji: "jj", sound: "jj", group: "tense-consonants" },
];

export const vowels = [
  { char: "ㅏ", romaji: "a", sound: "a", group: "basic-vowels-vertical" },
  { char: "ㅑ", romaji: "ya", sound: "ya", group: "basic-vowels-vertical" },
  { char: "ㅓ", romaji: "eo", sound: "eo", group: "basic-vowels-vertical" },
  { char: "ㅕ", romaji: "yeo", sound: "yeo", group: "basic-vowels-vertical" },
  { char: "ㅣ", romaji: "i", sound: "i", group: "basic-vowels-vertical" },

  { char: "ㅗ", romaji: "o", sound: "o", group: "basic-vowels-horizontal" },
  { char: "ㅛ", romaji: "yo", sound: "yo", group: "basic-vowels-horizontal" },
  { char: "ㅜ", romaji: "u", sound: "u", group: "basic-vowels-horizontal" },
  { char: "ㅠ", romaji: "yu", sound: "yu", group: "basic-vowels-horizontal" },
  { char: "ㅡ", romaji: "eu", sound: "eu", group: "basic-vowels-horizontal" },

  { char: "ㅐ", romaji: "ae", sound: "ae", group: "compound-vowels-vertical" },
  {
    char: "ㅒ",
    romaji: "yae",
    sound: "yae",
    group: "compound-vowels-vertical",
  },
  { char: "ㅔ", romaji: "e", sound: "e", group: "compound-vowels-vertical" },
  { char: "ㅖ", romaji: "ye", sound: "ye", group: "compound-vowels-vertical" },

  {
    char: "ㅘ",
    romaji: "wa",
    sound: "wa",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅙ",
    romaji: "wae",
    sound: "wae",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅚ",
    romaji: "oe",
    sound: "oe",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅝ",
    romaji: "wo",
    sound: "wo",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅞ",
    romaji: "we",
    sound: "we",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅟ",
    romaji: "wi",
    sound: "wi",
    group: "compound-vowels-horizontal",
  },
  {
    char: "ㅢ",
    romaji: "ui",
    sound: "ui",
    group: "compound-vowels-horizontal",
  },
];

export const syllables = [
  // Basic consonant + ㅏ (a)
  { char: "가", romaji: "ga", components: ["ㄱ", "ㅏ"], group: "syllable-ga" },
  { char: "나", romaji: "na", components: ["ㄴ", "ㅏ"], group: "syllable-na" },
  { char: "다", romaji: "da", components: ["ㄷ", "ㅏ"], group: "syllable-da" },
  { char: "라", romaji: "ra", components: ["ㄹ", "ㅏ"], group: "syllable-ra" },
  { char: "마", romaji: "ma", components: ["ㅁ", "ㅏ"], group: "syllable-ma" },
  { char: "바", romaji: "ba", components: ["ㅂ", "ㅏ"], group: "syllable-ba" },
  { char: "사", romaji: "sa", components: ["ㅅ", "ㅏ"], group: "syllable-sa" },
  { char: "아", romaji: "a", components: ["ㅇ", "ㅏ"], group: "syllable-a" },
  { char: "자", romaji: "ja", components: ["ㅈ", "ㅏ"], group: "syllable-ja" },
  {
    char: "차",
    romaji: "cha",
    components: ["ㅊ", "ㅏ"],
    group: "syllable-cha",
  },
  { char: "카", romaji: "ka", components: ["ㅋ", "ㅏ"], group: "syllable-ka" },
  { char: "타", romaji: "ta", components: ["ㅌ", "ㅏ"], group: "syllable-ta" },
  { char: "파", romaji: "pa", components: ["ㅍ", "ㅏ"], group: "syllable-pa" },
  { char: "하", romaji: "ha", components: ["ㅎ", "ㅏ"], group: "syllable-ha" },

  // Consonant + ㅓ (eo)
  {
    char: "거",
    romaji: "geo",
    components: ["ㄱ", "ㅓ"],
    group: "syllable-geo",
  },
  {
    char: "너",
    romaji: "neo",
    components: ["ㄴ", "ㅓ"],
    group: "syllable-neo",
  },
  {
    char: "더",
    romaji: "deo",
    components: ["ㄷ", "ㅓ"],
    group: "syllable-deo",
  },
  {
    char: "러",
    romaji: "reo",
    components: ["ㄹ", "ㅓ"],
    group: "syllable-reo",
  },
  {
    char: "머",
    romaji: "meo",
    components: ["ㅁ", "ㅓ"],
    group: "syllable-meo",
  },
  {
    char: "버",
    romaji: "beo",
    components: ["ㅂ", "ㅓ"],
    group: "syllable-beo",
  },
  {
    char: "서",
    romaji: "seo",
    components: ["ㅅ", "ㅓ"],
    group: "syllable-seo",
  },
  { char: "어", romaji: "eo", components: ["ㅇ", "ㅓ"], group: "syllable-eo" },
  {
    char: "저",
    romaji: "jeo",
    components: ["ㅈ", "ㅓ"],
    group: "syllable-jeo",
  },

  // Common words (optional)
  {
    char: "한글",
    romaji: "hangul",
    components: ["ㅎ", "ㅏ", "ㄴ", "ㄱ", "ㅡ", "ㄹ"],
    group: "words",
  },
  {
    char: "한국",
    romaji: "hanguk",
    components: ["ㅎ", "ㅏ", "ㄴ", "ㄱ", "ㅜ", "ㄱ"],
    group: "words",
  },
];

export const groupLabels = {
  "basic-consonants": "Basic consonants (g k n d t r l m b p s ng j)",
  "aspirated-consonants": "Aspirated (ch k t p h)",
  "tense-consonants": "Tense / doubled (kk tt pp ss jj)",
  "basic-vowels-vertical": "Basic vowels (a ya eo yeo i)",
  "basic-vowels-horizontal": "Basic vowels (o yo u yu eu)",
  "compound-vowels-vertical": "Compound vowels (ae yae e ye)",
  "compound-vowels-horizontal": "Compound vowels (wa wae oe wo we wi ui)",
  // syllable group labels
  "syllable-ga": "가 (ga) - ㄱ + ㅏ",
  "syllable-na": "나 (na) - ㄴ + ㅏ",
  "syllable-da": "다 (da) - ㄷ + ㅏ",
  "syllable-ra": "라 (ra) - ㄹ + ㅏ",
  "syllable-ma": "마 (ma) - ㅁ + ㅏ",
  "syllable-ba": "바 (ba) - ㅂ + ㅏ",
  "syllable-sa": "사 (sa) - ㅅ + ㅏ",
  "syllable-a": "아 (a) - ㅇ + ㅏ",
  "syllable-ja": "자 (ja) - ㅈ + ㅏ",
  "syllable-cha": "차 (cha) - ㅊ + ㅏ",
  "syllable-ka": "카 (ka) - ㅋ + ㅏ",
  "syllable-ta": "타 (ta) - ㅌ + ㅏ",
  "syllable-pa": "파 (pa) - ㅍ + ㅏ",
  "syllable-ha": "하 (ha) - ㅎ + ㅏ",
  "syllable-geo": "거 (geo) - ㄱ + ㅓ",
  "syllable-neo": "너 (neo) - ㄴ + ㅓ",
  "syllable-deo": "더 (deo) - ㄷ + ㅓ",
  "syllable-reo": "러 (reo) - ㄹ + ㅓ",
  "syllable-meo": "머 (meo) - ㅁ + ㅓ",
  "syllable-beo": "버 (beo) - ㅂ + ㅓ",
  "syllable-seo": "서 (seo) - ㅅ + ㅓ",
  "syllable-eo": "어 (eo) - ㅇ + ㅓ",
  "syllable-jeo": "저 (jeo) - ㅈ + ㅓ",
  words: "Common Words",
};

export const fonts = [
  { id: "default", label: "Default", family: "'Noto Sans KR', sans-serif" },
  { id: "serif", label: "Serif", family: "'Noto Serif KR', serif" },
  { id: "gothic", label: "Gothic", family: "'Black Han Sans', sans-serif" },
  { id: "dotum", label: "Dotum", family: "'Nanum Gothic', sans-serif" },
  { id: "myungjo", label: "Myungjo", family: "'Nanum Myeongjo', serif" },
];

export const ALL_GROUPS = Object.keys(groupLabels);

export const allChars = { consonants, vowels };
const CHO = [
  "ㄱ",
  "ㄲ",
  "ㄴ",
  "ㄷ",
  "ㄸ",
  "ㄹ",
  "ㅁ",
  "ㅂ",
  "ㅃ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅉ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];

const JUNG = [
  "ㅏ",
  "ㅐ",
  "ㅑ",
  "ㅒ",
  "ㅓ",
  "ㅔ",
  "ㅕ",
  "ㅖ",
  "ㅗ",
  "ㅘ",
  "ㅙ",
  "ㅚ",
  "ㅛ",
  "ㅜ",
  "ㅝ",
  "ㅞ",
  "ㅟ",
  "ㅠ",
  "ㅡ",
  "ㅢ",
  "ㅣ",
];

const JONG = [
  "",
  "ㄱ",
  "ㄲ",
  "ㄳ",
  "ㄴ",
  "ㄵ",
  "ㄶ",
  "ㄷ",
  "ㄹ",
  "ㄺ",
  "ㄻ",
  "ㄼ",
  "ㄽ",
  "ㄾ",
  "ㄿ",
  "ㅀ",
  "ㅁ",
  "ㅂ",
  "ㅄ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];
